### PR TITLE
Backport is_safe_url security fixes to django 1.7

### PR DESCRIPTION
**Pull request by belak**
```
~/C/v/d/tests [django] % PYTHONPATH=..:$PYTHONPATH ./runtests.py                                                                                                                                                                                                                                          x [belak/1.7.11-bb2]
Testing against Django installed in '/home/belak/Code/vendor/django/django'
Creating test database for alias 'default'...
Creating test database for alias 'other'...
.......................................................................................................................................................................................................................................................................................................................................................................................x........................s.....................................................................................................................................................................s........................................................................................................................................................................................s..................................................................................................................................................................s.............................................................................................................................................................................................................................................................................................s.....................................................................................................................................................................................................................................................................................................x.............................................s..............ss...ss..s.............................ss.ssssssss.......................................s......................................................................ssss...........................................s.......................................................................................................................................................ss...............................x....s.............x..................................................................................................................................................................................................................s...............................................................................ssssssssssss...................................................................................................s..............................................................................................................................................................................................................................................ss..ss...........................................................................................................................s.sss..sss......s.s....ss................................................................................................x...................................................s........................s.................s.......................................................xx............................................................................................s................................................................................................................................................................................ss.......................................................................sssssssss.............................................................................................................................................................................................................................................................................................................................................sss..................................s................x............................s...ssssssssssss.ssss...............s..........................................................................................................................................................................................................s.......................................s...........s..........................................s...............................................s...ssssssssssssssssssss......................................................................................................................................................ssssssssssssssssssssssssssssssssssssssssssss.........................................................................................................................................................................................sssssssssssssssssssssssssssssssssssssssssssss.............................................................................sss.........................................................................................................................................................................................sssssss....s.......ss.....s......s...ssss..s..s.s...............s.s......s.....................s.................................................................................................................................................s........................................................................................................................................................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss.....ss............................ssssss...........................................................................................................................................................................ss..ss......ssss......................................................................................................................................................sssssssssss................................................s..................................ss..............s.ss..s.s..ss......sss......s...s......ssssssssssssssss.............s.ssssssssssssssssssss.......................s....................ssssssssssssssssssss...s.......s...........s.ss.ssssss..........sss.........................................................s.........................................................................................ss......................................................sss................sssssssssssssssssssss............................................................................................ssssss..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................ss........................................................................................................................................................................................................ss.......ss...............................................................................sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss........................sssssss
----------------------------------------------------------------------
Ran 7396 tests in 211.371s

OK (skipped=638, expected failures=8)
Destroying test database for alias 'default'...
Destroying test database for alias 'other'...
```

### CODE REVIEW

**Comment by erikvanzijst** [comment]
LGTM

**Comment by mark-adams** [comment]
@belak Is there a reason this can't be monkeypatched in our bitbucket.util.patches?

We're trying to avoid making changes to the fork itself if they can be monkeypatched in the application.

**Comment by belak** [comment]
I wasn't aware of `bb.util.patches`. I'll check that out.

**Comment by belak** [comment]
This is a fairly complicated thing to monkey patch in. Most of our other patches simply wrap a view... this is massively more complicated than that. Not to mention the django tests would need to be ported over to our codebase. I would rather merge this in here and use it... once we're back on a newer version of django, we won't even need to worry about this patch.

**Comment by belak** [comment]
I meant to merge this rather than close it.

**Pull request merged**
